apiVersion: apps/v1
kind: Deployment
metadata:
  name: peter-nodejs
  namespace: peter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peter-nodejs
  template:
    metadata:
      labels:
        app: peter-nodejs
    spec:
      containers:
      - name: peter-nodejs
        image: devopsl/nodejs:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000