apiVersion: v1
kind: Service
metadata:
  name: service-peter
  namespace: peter
  labels: 
    app: peter-nodejs
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    type: LoadBalancer
  # - protocol: TCP
  #   port: 443
  #   name: https
  selector:
    app: peter-nodejs
  
